### ISSUE TITLE
NPM package.json

### ISSUE THREAD

**Issue by davehenke** [hunzaboy/Cool-Checkboxes-for-Bulma.io#1]
Thank you for your work on this.

I really like this stylesheet, but I'd like to be able to manage it as a dependency through `npm` or `yarn` instead of having to clone it and include it directly in my project's repository.

I would submit a PR for this, but I don't want to make any assumptions about your preferred `package.json` parameters.

**Comment by hunzaboy** [comment]
I have added the lib to npm and released package.json
https://www.npmjs.com/package/cool-checkboxes-for-bulma.io

Feel free to PR if something needs to be fixed.

**Comment by davehenke** [comment]
Thank you!
