### ISSUE TITLE
Overwritten modifier classes with Sass

### ISSUE THREAD

**Issue by guanzo** [hunzaboy/Cool-Checkboxes-for-Bulma.io#2]
Hi, i've overwritten the `is-primary` class to a different color in sass before importing bulma. Your css has hardcoded it to the default color. Any idea how i can gracefully combine the two, besides overwriting your css? Maybe provide a sass file for this package?

**Comment by hunzaboy** [comment]
I will add a sass version but for now i cannot do that. I will add it in the next release.
