### ISSUE TITLE
cool-checkboxes usage

### ISSUE THREAD

**Issue by YacineGameDev** [hunzaboy/Cool-Checkboxes-for-Bulma.io#4]
I'm not sure but to make my project work with cool-checkboxes-for-bulma.io I added : 
```@import '~cool-checkboxes-for-bulma.io/dist/css/bulma-radio-checkbox.css';```
to my main styles.css file. Is this normal because I can't find something in the documentation saying we have to do so to make it work.
Moreover, I want to remove the outline when I click on the checkbox, is there a way I can work this out?

**Comment by hunzaboy** [comment]
the path seems to be wrong. Can you verify whether its importing the correct css file.

**Comment by hunzaboy** [comment]
the outline can be removed by adding css to the focus of the label with outline: none;

**Comment by YacineGameDev** [comment]
it is importing the correct file I checked in the styles.js file which is created when the project is build.
For anyone who wants to remove the outline on the checkbox you have to do:
```
#... label::before{
    outline: none;
}
```

**Comment by hunzaboy** [comment]
Thanks.
