### ISSUE TITLE
Check Icon on checkbox checked not showing

### ISSUE THREAD

**Issue by askshinde** [hunzaboy/Cool-Checkboxes-for-Bulma.io#6]
checkbox checked but icon not showing

**Comment by bluestorm21** [comment]
@askshinde if you are using fontawesome in the css (dist) you will see a line like this :  

```
input[type="checkbox"].styled:checked + label:after {
     font-family: "FontAwesome";
     content: "";
}
```
in my case I replaced it by : 

```
input[type="checkbox"].styled:checked + label:after {
    font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f00c";
}
```
Source: https://origin.fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by hunzaboy** [comment]
@jimchild49 , can you create a pull request for FA5?
