### ISSUE TITLE
"tick" icon is not displayed

### ISSUE THREAD

**Issue by MakRatanakKh** [hunzaboy/Cool-Checkboxes-for-Bulma.io#7]
Hello.
I have an issue as my cool-checkbox doesn't display "tick" icon like this.
![image](https://user-images.githubusercontent.com/46364520/61194799-179b6d00-a6ee-11e9-979b-724d71122021.png)

my code:
`<div class="column">
                    <p class="title is-4">Cool Checkboxes</p>
                    <div class="field">
                        <div class="b-checkbox">
                            <input id="checkbox1" class="styled" checked type="checkbox">
                            <label for="checkbox1">
                                Is Default
                            </label>
                        </div>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-primary">
                            <input id="checkbox2" class="styled" checked type="checkbox">
                            <label for="checkbox2">
                                Is Primary
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-success">
                            <input id="checkbox3" class="styled" checked type="checkbox">
                            <label for="checkbox3">
                                Is Success
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-danger">
                            <input id="checkbox4" class="styled" checked type="checkbox">
                            <label for="checkbox4">
                                Is Danger
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-info">
                            <input id="checkbox5" class="styled" checked type="checkbox">
                            <label for="checkbox5">
                                Is Info
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-warning">
                            <input id="checkbox6" class="styled" checked type="checkbox">
                            <label for="checkbox6">
                                Is Warning
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-dark">
                            <input id="checkbox7" class="styled" checked type="checkbox">
                            <label for="checkbox7">
                                Is Dark
                            </label>
                        </div>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                        <div class="b-checkbox is-black">
                            <input id="checkbox8" class="styled" checked type="checkbox">
                            <label for="checkbox8">
                                Is Black
                            </label>
                        </div>
                        </p>
                    </div>
                </div>`

Please, help.
Thanks. 😃

**Comment by hunzaboy** [comment]
What browser are you using?

**Comment by hunzaboy** [comment]
Please include Fontawesome

**Comment by brecke** [comment]
This is what I get, after importing fontawesome (plus webfonts):

![Screenshot 2019-09-19 at 09 30 30](https://user-images.githubusercontent.com/19879/65227242-33d9d280-dac0-11e9-827b-6fcd46f88d0c.png)

EDIT: the demo page uses Bulma v0.4.1 and I'm trying this with the v0.7.3, so that explains a lot.

**Comment by hunzaboy** [comment]
Oh... thanks for the info. will update it.
